version: '3.8'

services:
  postgres: 
    container_name: bi_vison
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bi_vison